#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SCRIPT_SOURCE="$REPO_ROOT/scripts/bump-version.sh"
TEST_ROOT="$(mktemp -d)"

cleanup() {
  rm -rf "$TEST_ROOT"
}
trap cleanup EXIT

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

make_fixture() {
  local repo="$1"
  local yaml_body="$2"

  mkdir -p "$repo/scripts" "$repo/.hermes-plugin"
  cp "$SCRIPT_SOURCE" "$repo/scripts/bump-version.sh"
  cat >"$repo/.version-bump.json" <<'JSON'
{
  "files": [
    { "path": "package.json", "field": "version" },
    { "path": ".hermes-plugin/plugin.yaml", "field": "version" }
  ],
  "audit": { "exclude": [] }
}
JSON
  cat >"$repo/package.json" <<'JSON'
{
  "name": "fixture",
  "version": "1.2.3"
}
JSON
  printf '%s\n' "$yaml_body" >"$repo/.hermes-plugin/plugin.yaml"
}

happy_repo="$TEST_ROOT/happy"
make_fixture "$happy_repo" $'name: ultrapowers\nversion: 1.2.3'

/bin/bash "$happy_repo/scripts/bump-version.sh" --check >"$TEST_ROOT/check.out"
/bin/bash "$happy_repo/scripts/bump-version.sh" --audit >"$TEST_ROOT/audit.out"
/bin/bash "$happy_repo/scripts/bump-version.sh" 2.3.4 >"$TEST_ROOT/bump.out"

[[ "$(jq -r '.version' "$happy_repo/package.json")" == "2.3.4" ]] \
  || fail "JSON manifest was not bumped"
[[ "$(yq -r '.version' "$happy_repo/.hermes-plugin/plugin.yaml")" == "2.3.4" ]] \
  || fail "YAML manifest was not bumped"

jq -e '
  any(.files[];
    .path == ".hermes-plugin/plugin.yaml" and .field == "version")
' "$REPO_ROOT/.version-bump.json" >/dev/null \
  || fail "Hermes manifest is not registered"

# The audit matches whole version numbers: a longer version that merely starts
# with the current one (1.2.30, v11.2.3) is not a stray copy of it.
whole_repo="$TEST_ROOT/whole"
make_fixture "$whole_repo" $'name: ultrapowers\nversion: 1.2.3'
printf '# needs tool v1.2.30+ or 11.2.3\n' >"$whole_repo/notes.sh"
/bin/bash "$whole_repo/scripts/bump-version.sh" --audit >"$TEST_ROOT/whole.out"
grep -q 'All clear' "$TEST_ROOT/whole.out" \
  || fail "audit flagged a longer version as the current one: $(cat "$TEST_ROOT/whole.out")"
printf 'pinned at 1.2.3.\n' >"$whole_repo/stray.md"
/bin/bash "$whole_repo/scripts/bump-version.sh" --audit >"$TEST_ROOT/stray.out"
grep -q 'stray.md' "$TEST_ROOT/stray.out" \
  || fail "audit missed a stray copy of the current version: $(cat "$TEST_ROOT/stray.out")"

# An audit.exclude entry holding a slash is a path from the repo root: it skips
# that file, or everything under that directory, and nothing else. The same
# base name elsewhere in the repo is still scanned.
path_repo="$TEST_ROOT/paths"
make_fixture "$path_repo" $'name: ultrapowers\nversion: 1.2.3'
jq '.audit.exclude = [".agents/memory", ".githooks/pre-commit"]' \
  "$path_repo/.version-bump.json" >"$TEST_ROOT/paths.json"
mv "$TEST_ROOT/paths.json" "$path_repo/.version-bump.json"
mkdir -p "$path_repo/.agents/memory/gotchas" "$path_repo/.githooks" "$path_repo/other"
printf '<!-- generated by init 1.2.3 -->\n' >"$path_repo/.agents/memory/README.md"
printf '<!-- generated by init 1.2.3 -->\n' >"$path_repo/.agents/memory/gotchas/a.md"
printf '# generated by init 1.2.3\n' >"$path_repo/.githooks/pre-commit"
/bin/bash "$path_repo/scripts/bump-version.sh" --audit >"$TEST_ROOT/paths.out"
grep -q 'All clear' "$TEST_ROOT/paths.out" \
  || fail "audit flagged a file under an excluded path: $(cat "$TEST_ROOT/paths.out")"
printf 'pinned at 1.2.3\n' >"$path_repo/README.md"
printf '# pinned at 1.2.3\n' >"$path_repo/other/pre-commit"
printf 'pinned at 1.2.3\n' >"$path_repo/.agents/memory-notes.md"
/bin/bash "$path_repo/scripts/bump-version.sh" --audit >"$TEST_ROOT/paths2.out"
for stray in README.md other/pre-commit .agents/memory-notes.md; do
  grep -q "$path_repo/$stray:" "$TEST_ROOT/paths2.out" \
    || fail "a path exclude hid $stray: $(cat "$TEST_ROOT/paths2.out")"
done

invalid_repo="$TEST_ROOT/invalid"
make_fixture "$invalid_repo" $'name: ultrapowers\nversion: 123'
cp "$invalid_repo/package.json" "$TEST_ROOT/package.before"
cp "$invalid_repo/.hermes-plugin/plugin.yaml" "$TEST_ROOT/plugin.before"

if /bin/bash "$invalid_repo/scripts/bump-version.sh" 2.3.4 \
  >"$TEST_ROOT/invalid.out" 2>&1; then
  fail "bump accepted a non-string YAML version"
fi

cmp -s "$TEST_ROOT/package.before" "$invalid_repo/package.json" \
  || fail "JSON manifest changed before YAML validation failed"
cmp -s "$TEST_ROOT/plugin.before" "$invalid_repo/.hermes-plugin/plugin.yaml" \
  || fail "invalid YAML manifest changed"

# A missing jq must be reported as a missing tool, not as an unreadable
# manifest. Drop only the PATH entries that hold jq; skip when that would
# also remove the core tools the script needs (jq in /usr/bin on Linux).
nojq_path=""
IFS=':' read -r -a path_dirs <<<"$PATH"
for d in "${path_dirs[@]}"; do
  [[ -n "$d" ]] || continue
  if [[ -x "$d/jq" || -x "$d/jq.exe" ]]; then continue; fi
  nojq_path="${nojq_path:+$nojq_path:}$d"
done
if PATH="$nojq_path" command -v sed >/dev/null 2>&1 \
  && PATH="$nojq_path" command -v tr >/dev/null 2>&1 \
  && ! PATH="$nojq_path" command -v jq >/dev/null 2>&1; then
  nojq_repo="$TEST_ROOT/nojq"
  make_fixture "$nojq_repo" $'name: ultrapowers\nversion: 1.2.3'
  if PATH="$nojq_path" /bin/bash "$nojq_repo/scripts/bump-version.sh" 2.3.4 \
    >"$TEST_ROOT/nojq.out" 2>&1; then
    fail "bump-version succeeded without jq"
  fi
  grep -q "required tool 'jq' is not on PATH" "$TEST_ROOT/nojq.out" \
    || fail "missing jq was not reported as a missing tool: $(cat "$TEST_ROOT/nojq.out")"
else
  echo "SKIP: missing-jq case (jq shares a PATH directory with core tools)"
fi

# The scaffold marker, the hook and the injectors accept only plain dotted
# versions, so a prerelease or suffixed version must be refused here.
for bad in 1.3.0-beta.1 1.3.0+build 1.3.0rc1; do
  pre_repo="$TEST_ROOT/pre-$bad"
  make_fixture "$pre_repo" $'name: ultrapowers\nversion: 1.2.3'
  if /bin/bash "$pre_repo/scripts/bump-version.sh" "$bad" >"$TEST_ROOT/pre.out" 2>&1; then
    fail "bump-version accepted $bad"
  fi
  [[ "$(jq -r '.version' "$pre_repo/package.json")" == "1.2.3" ]] \
    || fail "package.json changed after refusing $bad"
done

echo "Version-bump tests passed"
